galaxy_info:
  author: zaxos
  description: Ansible role to install and configure Rootkit Hunter

  license: GPLv2

  min_ansible_version: 2.0

  platforms:
  - name: EL
    versions:
    - 7
  - name: Debian
    versions:
    - stretch

  galaxy_tags: [rootkit,hunter,security]

dependencies: []
